# Docker Compose version v2.29.7
services:
  cgstvg:
    image: cgstvg
    build: .
    volumes:
      - ./data:/app/data:ro
      - ./model_zoo:/app/model_zoo:ro
      # - ./output/baseline/vidstg/model_125000.pth:/app/output/vidstg/model_125000.pth:ro
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # count: 1
              device_ids: [ '0', '1' ]
              capabilities: [ gpu ]
